### ISSUE TITLE
veristat fails to build with libbpf_1.6.1

### ISSUE THREAD

**Issue by sudipm-mukherjee** [libbpf/veristat#17]
veristat is using `bpf_object__prepare` at https://github.com/libbpf/veristat/blob/main/src/veristat.c#L1612. But `bpf_object__prepare` is not marked as a public API in libbpf.

its declared at https://github.com/libbpf/libbpf/blob/master/src/libbpf.h#L255 and is not marked with `LIBBPF_API`. According to the libbpf naming convention mentioned at https://github.com/libbpf/libbpf/blob/master/docs/libbpf_naming_convention.rst#symbol-visibility, this symbol is hidden and not exported.

As a result, when I try to update `veristat` in Debian, which now has libbpf/1.6.1, the build fails with the error:
```
/usr/bin/ld: .output/veristat.o: in function `process_prog':
/<<PKGBUILDDIR>>/src/veristat.c:1612:(.text+0x46fc): undefined reference to `bpf_object__prepare'
collect2: error: ld returned 1 exit status
```

**Comment by anakryiko** [comment]
This was fixed in https://lore.kernel.org/bpf/20250819215119.37795-1-mykyta.yatsenko5@gmail.com/, we are going to sync this to Github and create 1.6.2 release. Thanks for reporting!

**Comment by anakryiko** [comment]
@sudipm-mukherjee please see https://github.com/libbpf/libbpf/releases/tag/v1.6.2
